name: flutter_ble_lib_example
description: Demonstrates how to use the flutter_ble_lib plugin.
version: 0.1.0+2
publish_to: "none"

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  rxdart: ^0.28.0
  fimber: ^0.7.0

  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_ble_lib:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/ti_logo.png
