group 'com.polidea.flutter_ble_lib'
version '2.3.2'

buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.12.3'
    }
}

rootProject.allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 36

    defaultConfig {
        minSdkVersion 29
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.9.1'
    implementation 'com.github.VladBontaValentin:MultiPlatformBleAdapter:master'
}
